apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImageUpdateAutomation
metadata:
  name: wordpress-auto
  namespace: flux-system
spec:
  interval: 1h
  sourceRef:
    kind: GitRepository
    name: flux-system
  git:
    checkout:
      ref:
        branch: feat/implementation
    commit:
      author:
        name: fluxcdbot
        email: fluxcdbot@example.com
      messageTemplate: "update WordPress image to {{range .Updated.Images}}{{println .}}{{end}}"
  update:
    path: ./apps/base/wordpress
    strategy: Setters
